CREATE TABLE PESSOA (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(18) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    MATRICULA VARCHAR(100) NOT NULL,
    DIA_PAGAMENTO INT NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    ENDERECO VARCHAR(255),
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(11),
    TIPO_PESSOA VARCHAR(20) NOT NULL,
    DATA_CANCELAMENTO DATE,
    DATA_DESLIGAMENTO DATE,
    CONSTRAINT PK_PESSOA PRIMARY KEY (ID)
);

